Use template variables

diff --git a/templates/s3ql-init.j2 b/templates/s3ql-init.j2
--- a/templates/s3ql-init.j2
+++ b/templates/s3ql-init.j2
@@ -6,17 +6,13 @@
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Description:       S3QL is a filesystem that stores all its data online
-#                    on Amazon s3 and other backends
 ### END INIT INFO
 # init script for Debian or Alpine
 
 DESC="S3QL filesystem"
 AUTHFILE="{{ s3ql_authinfo_file }}"
-STORAGE_URL="{{ s3ql_storage_url }}/{{ s3ql_prefix }}"
-MOUNTPOINT="{{ s3ql_mountpoint }}"
 
-mkdir -p $MOUNTPOINT
-# put all s3ql logs here
+mkdir -p {{ s3ql_mountpoint }}
 mkdir -p /var/log/s3ql
 
 case "$1" in
@@ -29,13 +25,13 @@ case "$1" in
     exec 2>&1
     rm -rf "$DIR"
 
-	if mountpoint -q "$MOUNTPOINT"; then
-        echo "ERROR: $DESC $STORAGE_URL is already mounted on $MOUNTPOINT"
+	if mountpoint -q "{{ s3ql_mountpoint }}"; then
+        echo "ERROR: $DESC {{ s3ql_storage_url }}/{{ s3ql_prefix }} is already mounted on {{ s3ql_mountpoint }}"
 		exit 1
 	fi
-	echo "Mounting $DESC" "$STORAGE_URL on $MOUNTPOINT"
+	echo "Mounting $DESC" "{{ s3ql_storage_url }}/{{ s3ql_prefix }} on {{ s3ql_mountpoint }}"
 	# Check and mount file system
-	fsck.s3ql --batch --log /var/log/s3ql/fsck.log --authfile "$AUTHFILE" "$STORAGE_URL"
+	fsck.s3ql --batch --log /var/log/s3ql/fsck.log --authfile {{ s3ql_authinfo_file }} {{ s3ql_storage_url }}/{{ s3ql_prefix }}
 	STA=$?
 	if [ $STA -eq 0 ]; then
         echo "successfully checked filesystem"
@@ -43,9 +39,9 @@ case "$1" in
         echo "ERROR: this is the error code: $STA"
 		exit $STA
 	fi
-	mount.s3ql --log /var/log/s3ql/mount.log --authfile "$AUTHFILE" "$STORAGE_URL" "$MOUNTPOINT"
+	mount.s3ql --log /var/log/s3ql/mount.log --authfile {{ s3ql_authinfo_file }} {{ s3ql_storage_url }}/{{ s3ql_prefix }} {{ s3ql_mountpoint }}
 	if [ $STA -eq 0 ]; then
-        echo "successfully mounted on $MOUNTPOINT"
+        echo "successfully mounted on {{ s3ql_mountpoint }}"
     else
         echo "ERROR: this is the error code: $STA"
 		exit $STA
@@ -60,28 +56,28 @@ case "$1" in
     exec 2>&1
     rm -rf "$DIR"
 
-	if ! mountpoint -q "$MOUNTPOINT"; then
-        echo "ERROR: $DESC $STORAGE_URL is currently not mounted on $MOUNTPOINT"
+	if ! mountpoint -q "{{ s3ql_mountpoint }}"; then
+        echo "ERROR: $DESC {{ s3ql_storage_url }}/{{ s3ql_prefix }} is currently not mounted on {{ s3ql_mountpoint }}"
         exit 1
     fi
-	echo "Unmounting $DESC $STORAGE_URL from $MOUNTPOINT"
-        s3qlctrl flushcache "$MOUNTPOINT"
-	      s3qlctrl upload-meta "$MOUNTPOINT"
-        umount.s3ql "$MOUNTPOINT"
+	echo "Unmounting $DESC {{ s3ql_storage_url }}/{{ s3ql_prefix }} from {{ s3ql_mountpoint }}"
+        s3qlctrl flushcache {{ s3ql_mountpoint }}
+	      s3qlctrl upload-meta {{ s3ql_mountpoint }}
+        umount.s3ql {{ s3ql_mountpoint }}
 	if [ $? -eq 0 ]; then
-        echo "successfully unmounted $MOUNTPOINT"
+        echo "successfully unmounted {{ s3ql_mountpoint }}"
     else
         echo "ERROR: this is the error code: $STA"
 		exit $STA
 	fi
 	;;
   status)
-	if ! mountpoint -q "$MOUNTPOINT"; then
-        echo "$DESC $STORAGE_URL is currently not mounted on $MOUNTPOINT"
+	if ! mountpoint -q {{ s3ql_mountpoint }}; then
+        echo "$DESC {{ s3ql_storage_url }}/{{ s3ql_prefix }} is currently not mounted on {{ s3ql_mountpoint }}"
         exit 1
     fi
-    echo "Status of $DESC $STORAGE_URL on $MOUNTPOINT"
-	s3qlstat "$MOUNTPOINT"
+    echo "Status of $DESC {{ s3ql_storage_url }}/{{ s3ql_prefix }} on {{ s3ql_mountpoint }}"
+	s3qlstat {{ s3ql_mountpoint }}
 	exit "$?"
 	;;
   *)
